export const COVERAGES_TYPES = [
  {
    id: 'CARGO',
    name: 'Cargo',
    help: 'Will prefill Acord 22, Acord 25',
    iconLabel: 'C',
  },
  {
    id: 'EXCESS_UMBRELLA_LIABILITY',
    name: 'Excess/Umbrella Liability',
    help: 'Will prefill Acord 22, Acord 25',
    iconLabel: 'Umb',
  },
  {
    id: 'GENERAL_LIABILITY',
    name: 'General Liability',
    help: 'Will prefill Acord 22, Acord 25',
    iconLabel: 'GL',
  },
  {
    id: 'PHYSICAL_DAMAGE',
    name: 'Physical Damage',
    help: 'Physical Damage',
    iconLabel: 'PD',
  },
  {
    id: 'ACORD_27',
    name: 'Acord 27',
    help: 'Acord 27',
    iconLabel: 'A27',
  },
  {
    id: 'AGRICULTURAL_LIABILITY',
    name: 'Agricultural Liability',
    help: 'Agricultural Liability',
    iconLabel: 'AgL',
  },
  {
    id: 'AUTOMOBILE_LIABILITY',
    name: 'Automobile Liability',
    help: 'Will prefill Acord 22, Acord 25',
    iconLabel: 'AuL',
  },
  {
    id: 'BOILER_AND_MACHINERY_EQUIPMENT_BREAKDOWN',
    name: 'Boiler And Machinery / Equipment Breakdown',
    help: 'Will prefill Acord 24',
    iconLabel: 'BMEB',
  },
  {
    id: 'CONTINGENT_AUTO_LIABILITY',
    name: 'Contingent Auto Liability',
    help: 'Contingent Auto Liability',
    iconLabel: 'CAuL',
  },
  {
    id: 'CONTINGENT_CARGO',
    name: 'Contingent Cargo',
    help: 'Will prefill Acord 25',
    iconLabel: 'CC',
  },
  {
    id: 'COVERAGE_INFORMATION',
    name: 'Coverage Information',
    help: 'Will prefill Acord 28',
    iconLabel: 'CI',
  },
  {
    id: 'CRIME_24',
    name: 'Crime(24)',
    help: 'Will prefill Acord 24',
    iconLabel: 'Cri',
  },
  {
    id: 'FLOOD_COVERAGE_EXCESS_POLICY',
    name: 'Flood Coverage / Excess Policy',
    help: 'Will prefill Acord 29',
    iconLabel: 'FCEP',
  },
  {
    id: 'FLOOD_COVERAGE_PRIMARY_POLICY',
    name: 'Flood Coverage / Primary Policy',
    help: 'Will prefill Acord 29',
    iconLabel: 'FCPP',
  },
  {
    id: 'GARAGE_KEEPERS_LIABILITY',
    name: 'Garage Keepers Liability',
    help: 'Will prefill Acord 30',
    iconLabel: 'GaKL',
  },
  {
    id: 'GARAGE_LIABILITY',
    name: 'Garage Liability',
    help: 'Will prefill Acord 30',
    iconLabel: 'GaL',
  },
  {
    id: 'INLAND_MARINE',
    name: 'Inland Marine',
    help: 'Will prefill Acord 24',
    iconLabel: 'IM',
  },
  {
    id: 'LIFE_AND_HEALTH',
    name: 'Life And Health',
    help: 'Life & Health',
    iconLabel: 'LH',
  },
  {
    id: 'OCCUPATIONAL_ACCIDENT',
    name: 'Occupational Accident',
    help: 'Occupational Accident',
    iconLabel: 'OA',
  },
  {
    id: 'OTHER',
    name: 'Other',
    help: 'Other',
    iconLabel: 'Oth',
  },
  {
    id: 'PROPERTY_24',
    name: 'Property (24)',
    help: 'Will prefill Acord 24',
    iconLabel: 'P24',
  },
  {
    id: 'REEFER_BREAKDOWN',
    name: 'Reefer Breakdown',
    help: 'Reefer Breakdown',
    iconLabel: 'RB',
  },
  {
    id: 'TRAILER_INTERCHANGE_PHYSICAL_DAMAGE',
    name: 'Trailer Interchange Physical Damage',
    help: 'Will prefill Acord 22',
    iconLabel: 'TIPD',
  },
  {
    id: 'UNDERINSURED_MOTORISTS',
    name: 'Underinsured Motorists',
    help: 'Underinsured Motorists',
    iconLabel: 'UndM',
  },
  {
    id: 'UNINSURED_MOTORISTS',
    name: 'Uninsured Motorists',
    help: 'Uninsured Motorists',
    iconLabel: 'UniM',
  },
  {
    id: 'WORKERS_COMPENSATION_AND_EMPLOYERS_LIABILITY',
    name: 'Workers Compensation And Employers Liability',
    help: 'Will prefill Acord 22, Acord 25',
    iconLabel: 'WCEL',
  },
];
