export const ENDORSEMENT_ITEM_TYPES = {
  PAYABLE: [
    { name: 'Down Payment', id: 'DOWN_PAYMENT' },
    { name: 'Paid in Full', id: 'PAID_IN_FULL' },
    { name: 'Installment', id: 'INSTALLMENT' },
    { name: 'Other', id: 'OTHER' },
  ],
  RECEIVABLE: [
    { name: 'Down Payment', id: 'DOWN_PAYMENT' },
    { name: 'Paid in Full', id: 'PAID_IN_FULL' },
    { name: 'Installment', id: 'INSTALLMENT' },
    { name: 'Other', id: 'OTHER' },
  ],
  FINANCING_DIRECT_BILL: [
    { name: 'Direct Bill', id: 'DIRECT_BILL' },
    { name: 'Inside Financing', id: 'INSIDE_FINANCING' },
    { name: 'Outside Financing', id: 'OUTSIDE_FINANCING' },
    { name: 'Other', id: 'OTHER' },
  ],
  FEE_TAX: [
    { name: 'Agency Fee', id: 'AGENCY_FEE' },
    { name: 'Carrier Policy Fee', id: 'CARRIER_POLICY_FEE' },
    { name: 'Broker/MGA Fee', id: 'BROKER_MGA_FEE' },
    { name: 'Inspection Fee', id: 'INSPECTION_FEE' },
    { name: 'AI Endorsements Fee', id: 'AI_ENDORSEMENTS_FEE' },
    { name: 'Subscription Fee', id: 'SUBSCRIPTION_FEE' },
    { name: 'Program Fee', id: 'PROGRAM_FEE' },
    { name: 'Processing Fee', id: 'PROCESSING_FEE' },
    { name: 'Other Fees', id: 'OTHER_FEES' },
    { name: 'Taxes', id: 'TAXES' },
    { name: 'State Tax', id: 'STATE_TAX' },
    { name: 'Surplus Lines Tax', id: 'SURPLUS_LINES_TAX' },
    { name: 'APTC - Tax Credit', id: 'APTC_TAX_CREDIT' },
    { name: 'Stamping Fee', id: 'STAMPING_FEE' },
    {
      name: 'Miscellaneous Agency Revenue',
      id: 'MISCELLANEOUS_AGENCY_REVENUE',
    },
    { name: 'Other Tax', id: 'OTHER_TAX' },
    { name: 'Expense Constant', id: 'EXPENSE_CONSTANT' },
    { name: 'Surplus Contribution', id: 'SURPLUS_CONTRIBUTION' },
    { name: 'AB/TPA Fee', id: 'AB_TPA_FEE' },
    {
      name: 'Independent Agent/Broker Fee',
      id: 'INDEPENDENT_AGENT_BROKER_FEE',
    },
    { name: 'Payment Processing Fee', id: 'PAYMENT_PROCESSING_FEE' },
    { name: 'Risk Management Fee', id: 'RISK_MANAGEMENT_FEE' },
    { name: 'Policy Fee', id: 'POLICY_FEE' },
    { name: 'Fire Marshall Tax', id: 'FIRE_MARSHALL_TAX' },
    { name: 'Filing Fee', id: 'FILING_FEE' },
    { name: 'Other', id: 'OTHER' },
  ],
/*   AGENCY_COMMISSION: [
    { name: 'Gross', id: 'GROSS' },
    { name: 'Monthly - Net', id: 'MONTHLY_NET' },
    { name: 'Net', id: 'NET' },
    { name: 'Month Earned', id: 'MONTH_EARNED' },
  ],
  AGENTS_COMMISSION: [
    { name: 'From Agency Commission', id: 'FROM_AGENCY_COMMISSION' },
    { name: 'From Base Premium', id: 'FROM_BASE_PREMIUM' },
    { name: 'From Finance Company Incentive', id: 'FROM_FINANCE_COMPANY_INCENTIVE' },
    { name: 'Fee', id: 'FEE' },
  ], */
};
