export const Industries = [
  { id: '', name: 'Any' },
  { id: 'stocksonly', name: 'Stocks only (ex-Funds)' },
  { id: 'exchangetradedfund', name: 'Exchange Traded Fund' },
  { id: 'advertisingagencies', name: 'Advertising Agencies' },
  { id: 'aerospacedefense', name: 'Aerospace &amp; Defense' },
  { id: 'agriculturalinputs', name: 'Agricultural Inputs' },
  { id: 'airlines', name: 'Airlines' },
  { id: 'airportsairservices', name: 'Airports &amp; Air Services' },
  { id: 'aluminum', name: 'Aluminum' },
  { id: 'apparelmanufacturing', name: 'Apparel Manufacturing' },
  { id: 'apparelretail', name: 'Apparel Retail' },
  { id: 'assetmanagement', name: 'Asset Management' },
  { id: 'automanufacturers', name: 'Auto Manufacturers' },
  { id: 'autoparts', name: 'Auto Parts' },
  { id: 'autotruckdealerships', name: 'Auto &amp; Truck Dealerships' },
  { id: 'banksdiversified', name: 'Banks - Diversified' },
  { id: 'banksregional', name: 'Banks - Regional' },
  { id: 'beveragesbrewers', name: 'Beverages - Brewers' },
  { id: 'beveragesnonalcoholic', name: 'Beverages - Non-Alcoholic' },
  {
    id: 'beverageswineriesdistilleries',
    name: 'Beverages - Wineries &amp; Distilleries',
  },
  { id: 'biotechnology', name: 'Biotechnology' },
  { id: 'broadcasting', name: 'Broadcasting' },
  { id: 'buildingmaterials', name: 'Building Materials' },
  {
    id: 'buildingproductsequipment',
    name: 'Building Products &amp; Equipment',
  },
  {
    id: 'businessequipmentsupplies',
    name: 'Business Equipment &amp; Supplies',
  },
  { id: 'capitalmarkets', name: 'Capital Markets' },
  { id: 'chemicals', name: 'Chemicals' },
  { id: 'closedendfunddebt', name: 'Closed-End Fund - Debt' },
  { id: 'closedendfundequity', name: 'Closed-End Fund - Equity' },
  { id: 'closedendfundforeign', name: 'Closed-End Fund - Foreign' },
  { id: 'cokingcoal', name: 'Coking Coal' },
  { id: 'communicationequipment', name: 'Communication Equipment' },
  { id: 'computerhardware', name: 'Computer Hardware' },
  { id: 'confectioners', name: 'Confectioners' },
  { id: 'conglomerates', name: 'Conglomerates' },
  { id: 'consultingservices', name: 'Consulting Services' },
  { id: 'consumerelectronics', name: 'Consumer Electronics' },
  { id: 'copper', name: 'Copper' },
  { id: 'creditservices', name: 'Credit Services' },
  { id: 'departmentstores', name: 'Department Stores' },
  { id: 'diagnosticsresearch', name: 'Diagnostics &amp; Research' },
  { id: 'discountstores', name: 'Discount Stores' },
  { id: 'drugmanufacturersgeneral', name: 'Drug Manufacturers - General' },
  {
    id: 'drugmanufacturersspecialtygeneric',
    name: 'Drug Manufacturers - Specialty &amp; Generic',
  },
  {
    id: 'educationtrainingservices',
    name: 'Education &amp; Training Services',
  },
  { id: 'electricalequipmentparts', name: 'Electrical Equipment &amp; Parts' },
  { id: 'electroniccomponents', name: 'Electronic Components' },
  {
    id: 'electronicgamingmultimedia',
    name: 'Electronic Gaming &amp; Multimedia',
  },
  {
    id: 'electronicscomputerdistribution',
    name: 'Electronics &amp; Computer Distribution',
  },
  { id: 'engineeringconstruction', name: 'Engineering &amp; Construction' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'exchangetradedfund', name: 'Exchange Traded Fund' },
  {
    id: 'farmheavyconstructionmachinery',
    name: 'Farm &amp; Heavy Construction Machinery',
  },
  { id: 'farmproducts', name: 'Farm Products' },
  { id: 'financialconglomerates', name: 'Financial Conglomerates' },
  {
    id: 'financialdatastockexchanges',
    name: 'Financial Data &amp; Stock Exchanges',
  },
  { id: 'fooddistribution', name: 'Food Distribution' },
  { id: 'footwearaccessories', name: 'Footwear &amp; Accessories' },
  {
    id: 'furnishingsfixturesappliances',
    name: 'Furnishings, Fixtures &amp; Appliances',
  },
  { id: 'gambling', name: 'Gambling' },
  { id: 'gold', name: 'Gold' },
  { id: 'grocerystores', name: 'Grocery Stores' },
  { id: 'healthcareplans', name: 'Healthcare Plans' },
  { id: 'healthinformationservices', name: 'Health Information Services' },
  { id: 'homeimprovementretail', name: 'Home Improvement Retail' },
  {
    id: 'householdpersonalproducts',
    name: 'Household &amp; Personal Products',
  },
  { id: 'industrialdistribution', name: 'Industrial Distribution' },
  {
    id: 'informationtechnologyservices',
    name: 'Information Technology Services',
  },
  { id: 'infrastructureoperations', name: 'Infrastructure Operations' },
  { id: 'insurancebrokers', name: 'Insurance Brokers' },
  { id: 'insurancediversified', name: 'Insurance - Diversified' },
  { id: 'insurancelife', name: 'Insurance - Life' },
  {
    id: 'insurancepropertycasualty',
    name: 'Insurance - Property &amp; Casualty',
  },
  { id: 'insurancereinsurance', name: 'Insurance - Reinsurance' },
  { id: 'insurancespecialty', name: 'Insurance - Specialty' },
  {
    id: 'integratedfreightlogistics',
    name: 'Integrated Freight &amp; Logistics',
  },
  {
    id: 'internetcontentinformation',
    name: 'Internet Content &amp; Information',
  },
  { id: 'internetretail', name: 'Internet Retail' },
  { id: 'leisure', name: 'Leisure' },
  { id: 'lodging', name: 'Lodging' },
  { id: 'lumberwoodproduction', name: 'Lumber &amp; Wood Production' },
  { id: 'luxurygoods', name: 'Luxury Goods' },
  { id: 'marineshipping', name: 'Marine Shipping' },
  { id: 'medicalcarefacilities', name: 'Medical Care Facilities' },
  { id: 'medicaldevices', name: 'Medical Devices' },
  { id: 'medicaldistribution', name: 'Medical Distribution' },
  {
    id: 'medicalinstrumentssupplies',
    name: 'Medical Instruments &amp; Supplies',
  },
  { id: 'metalfabrication', name: 'Metal Fabrication' },
  { id: 'mortgagefinance', name: 'Mortgage Finance' },
  { id: 'oilgasdrilling', name: 'Oil &amp; Gas Drilling' },
  { id: 'oilgasep', name: 'Oil &amp; Gas E&amp;P' },
  {
    id: 'oilgasequipmentservices',
    name: 'Oil &amp; Gas Equipment &amp; Services',
  },
  { id: 'oilgasintegrated', name: 'Oil &amp; Gas Integrated' },
  { id: 'oilgasmidstream', name: 'Oil &amp; Gas Midstream' },
  {
    id: 'oilgasrefiningmarketing',
    name: 'Oil &amp; Gas Refining &amp; Marketing',
  },
  {
    id: 'otherindustrialmetalsmining',
    name: 'Other Industrial Metals &amp; Mining',
  },
  {
    id: 'otherpreciousmetalsmining',
    name: 'Other Precious Metals &amp; Mining',
  },
  { id: 'packagedfoods', name: 'Packaged Foods' },
  { id: 'packagingcontainers', name: 'Packaging &amp; Containers' },
  { id: 'paperpaperproducts', name: 'Paper &amp; Paper Products' },
  { id: 'personalservices', name: 'Personal Services' },
  { id: 'pharmaceuticalretailers', name: 'Pharmaceutical Retailers' },
  {
    id: 'pollutiontreatmentcontrols',
    name: 'Pollution &amp; Treatment Controls',
  },
  { id: 'publishing', name: 'Publishing' },
  { id: 'railroads', name: 'Railroads' },
  { id: 'realestatedevelopment', name: 'Real Estate - Development' },
  { id: 'realestatediversified', name: 'Real Estate - Diversified' },
  { id: 'realestateservices', name: 'Real Estate Services' },
  { id: 'recreationalvehicles', name: 'Recreational Vehicles' },
  { id: 'reitdiversified', name: 'REIT - Diversified' },
  { id: 'reithealthcarefacilities', name: 'REIT - Healthcare Facilities' },
  { id: 'reithotelmotel', name: 'REIT - Hotel &amp; Motel' },
  { id: 'reitindustrial', name: 'REIT - Industrial' },
  { id: 'reitmortgage', name: 'REIT - Mortgage' },
  { id: 'reitoffice', name: 'REIT - Office' },
  { id: 'reitresidential', name: 'REIT - Residential' },
  { id: 'reitretail', name: 'REIT - Retail' },
  { id: 'reitspecialty', name: 'REIT - Specialty' },
  { id: 'rentalleasingservices', name: 'Rental &amp; Leasing Services' },
  { id: 'residentialconstruction', name: 'Residential Construction' },
  { id: 'resortscasinos', name: 'Resorts &amp; Casinos' },
  { id: 'restaurants', name: 'Restaurants' },
  {
    id: 'scientifictechnicalinstruments',
    name: 'Scientific &amp; Technical Instruments',
  },
  {
    id: 'securityprotectionservices',
    name: 'Security &amp; Protection Services',
  },
  {
    id: 'semiconductorequipmentmaterials',
    name: 'Semiconductor Equipment &amp; Materials',
  },
  { id: 'semiconductors', name: 'Semiconductors' },
  { id: 'shellcompanies', name: 'Shell Companies' },
  { id: 'silver', name: 'Silver' },
  { id: 'softwareapplication', name: 'Software - Application' },
  { id: 'softwareinfrastructure', name: 'Software - Infrastructure' },
  { id: 'solar', name: 'Solar' },
  { id: 'specialtybusinessservices', name: 'Specialty Business Services' },
  { id: 'specialtychemicals', name: 'Specialty Chemicals' },
  {
    id: 'specialtyindustrialmachinery',
    name: 'Specialty Industrial Machinery',
  },
  { id: 'specialtyretail', name: 'Specialty Retail' },
  {
    id: 'staffingemploymentservices',
    name: 'Staffing &amp; Employment Services',
  },
  { id: 'steel', name: 'Steel' },
  { id: 'telecomservices', name: 'Telecom Services' },
  { id: 'textilemanufacturing', name: 'Textile Manufacturing' },
  { id: 'thermalcoal', name: 'Thermal Coal' },
  { id: 'tobacco', name: 'Tobacco' },
  { id: 'toolsaccessories', name: 'Tools &amp; Accessories' },
  { id: 'travelservices', name: 'Travel Services' },
  { id: 'trucking', name: 'Trucking' },
  { id: 'uranium', name: 'Uranium' },
  { id: 'utilitiesdiversified', name: 'Utilities - Diversified' },
  {
    id: 'utilitiesindependentpowerproducers',
    name: 'Utilities - Independent Power Producers',
  },
  { id: 'utilitiesregulatedelectric', name: 'Utilities - Regulated Electric' },
  { id: 'utilitiesregulatedgas', name: 'Utilities - Regulated Gas' },
  { id: 'utilitiesregulatedwater', name: 'Utilities - Regulated Water' },
  { id: 'utilitiesrenewable', name: 'Utilities - Renewable' },
  { id: 'wastemanagement', name: 'Waste Management' },
  { id: 'modal', name: 'Custom (Elite only)' },
];
