export const LINES_OF_BUSINESS = [
    { name: 'Commercial Auto', id: 'COMMERCIAL_AUTO'},
    { name: 'Personal Auto', id: 'PERSONAL_AUTO'},
    { name: 'Homeowners', id: 'HOMEOWNERS'},
    { name: 'General Liability', id: 'GENERAL_LIABILITY'},
    { name: 'Business Owners', id: 'BUSINESS_OWNERS'},
    { name: 'Worker\'s Compensation', id: 'WORKERS_COMPENSATION'},
    { name: 'Advertising/Media Liability', id: 'ADVERTISING_MEDIA_LIABILITY'},
    { name: 'Agriculture Liability', id: 'AGRICULTURE_LIABILITY'},
    { name: 'Agriculture Package', id: 'AGRICULTURE_PACKAGE'},
    { name: 'Agriculture Property', id: 'AGRICULTURE_PROPERTY'},
    { name: 'Agriculture Scheduled & Unscheduled Personal Property', id: 'AGRICULTURE_SCHEDULED___UNSCHEDULED_PERSONAL_PROPERTY'},
    { name: 'Aircraft - Commercial', id: 'AIRCRAFT___COMMERCIAL'},
    { name: 'Aircraft - Pleasure & Business', id: 'AIRCRAFT___PLEASURE_BUSINESS'},
    { name: 'Airport & Fixed Base Operator', id: 'AIRPORT___FIXED_BASE_OPERATOR'},
    { name: 'Annual Liability Premium', id: 'ANNUAL_LIABILITY_PREMIUM'},
    { name: 'Annual Physical Damage', id: 'ANNUAL_PHYSICAL_DAMAGE'},
    { name: 'Antique Auto', id: 'ANTIQUE_AUTO'},
    { name: 'Apartments', id: 'APARTMENTS'},
    { name: 'Bid Bond', id: 'BID_BOND'},
    { name: 'Boiler and Machinery', id: 'BOILER_AND_MACHINERY'},
    { name: 'Bond - Misc.', id: 'BOND___MISC.'},
    { name: 'BOP Liability', id: 'BOP_LIABILITY'},
    { name: 'BOP Property', id: 'BOP_PROPERTY'},
    { name: 'Commercial articles', id: 'COMMERCIAL_ARTICLES'},
    { name: 'Commercial fire', id: 'COMMERCIAL_FIRE'},
    { name: 'Commercial Inland Marine', id: 'COMMERCIAL_INLAND_MARINE'},
    { name: 'Commercial package', id: 'COMMERCIAL_PACKAGE'},
    { name: 'Commercial Property', id: 'COMMERCIAL_PROPERTY'},
    { name: 'Commercial Umbrella', id: 'COMMERCIAL_UMBRELLA'},
    { name: 'Comprehensive Personal Liability', id: 'COMPREHENSIVE_PERSONAL_LIABILITY'},
    { name: 'Computers', id: 'COMPUTERS'},
    { name: 'Condo owners - Personal', id: 'CONDO_OWNERS___PERSONAL'},
    { name: 'Condominium (HO-6)', id: 'CONDOMINIUM_HO_6'},
    { name: 'Contractors Bond', id: 'CONTRACTORS_BOND'},
    { name: 'Contractor\'s equipment floater', id: 'CONTRACTOR_S_EQUIPMENT_FLOATER'},
    { name: 'Course of Construction', id: 'COURSE_OF_CONSTRUCTION'},
    { name: 'Crime', id: 'CRIME'},
    { name: 'Cyber/Network Liability', id: 'CYBER_NETWORK_LIABILITY'},
    { name: 'D.I.C. - Commercial ', id: 'DIC_COMMERCIAL'},
    { name: 'D.I.C. - Personal ', id: 'DIC_PERSONAL'},
    { name: 'Dental', id: 'DENTAL'},
    { name: 'Directors and Officers', id: 'DIRECTORS_AND_OFFICERS'},
    { name: 'Disability - Group', id: 'DISABILITY___GROUP'},
    { name: 'Disability - Individual', id: 'DISABILITY___INDIVIDUAL'},
    { name: 'Dwelling Fire', id: 'DWELLING_FIRE'},
    { name: 'Earthquake', id: 'EARTHQUAKE'},
    { name: 'Employers Liability', id: 'EMPLOYERS_LIABILITY'},
    { name: 'Employment Practices Liability', id: 'EMPLOYMENT_PRACTICES_LIABILITY'},
    { name: 'Employment Related Practices Liability', id: 'EMPLOYMENT_RELATED_PRACTICES_LIABILITY'},
    { name: 'Errors And Omissions', id: 'ERRORS_AND_OMISSIONS'},
    { name: 'Excess Employment Related Practices Liab.', id: 'EXCESS_EMPLOYMENT_RELATED_PRACTICES_LIAB'},
    { name: 'Excess Liability', id: 'EXCESS_LIABILITY'},
    { name: 'Excess Professional Liability', id: 'EXCESS_PROFESSIONAL_LIABILITY'},
    { name: 'Excess Umbrella', id: 'EXCESS_UMBRELLA'},
    { name: 'Excess Umbrella - Personal', id: 'EXCESS_UMBRELLA___PERSONAL'},
    { name: 'Fiduciary', id: 'FIDUCIARY'},
    { name: 'FineArts', id: 'FINEARTS'},
    { name: 'Flood', id: 'FLOOD'},
    { name: 'Garage And Dealers', id: 'GARAGE_AND_DEALERS'},
    { name: 'Glass', id: 'GLASS'},
    { name: 'Hail', id: 'HAIL'},
    { name: 'Health', id: 'HEALTH'},
    { name: 'Installation/builders risk', id: 'INSTALLATION_BUILDERS_RISK'},
    { name: 'Internet Liability', id: 'INTERNET_LIABILITY'},
    { name: 'Kidnap And Ransom', id: 'KIDNAP_AND_RANSOM'},
    { name: 'License and Permit Bond', id: 'LICENSE_AND_PERMIT_BOND'},
    { name: 'Life', id: 'LIFE'},
    { name: 'Liquor Liability', id: 'LIQUOR_LIABILITY'},
    { name: 'Medical - Group', id: 'MEDICAL___GROUP'},
    { name: 'Miscellaneous Professional Liability', id: 'MISCELLANEOUS_PROFESSIONAL_LIABILITY'},
    { name: 'Mobile Homeowners', id: 'MOBILE_HOMEOWNERS'},
    { name: 'Motor Carrier', id: 'MOTOR_CARRIER'},
    { name: 'Motor Truck Cargo', id: 'MOTOR_TRUCK_CARGO'},
    { name: 'Motor Truck Cargo Carrier\'s Liability', id: 'MOTOR_TRUCK_CARGO_CARRIERS_LIABILITY'},
    { name: 'Motorcycle', id: 'MOTORCYCLE'},
    { name: 'Ocean Marine Commercial', id: 'OCEAN_MARINE_COMMERCIAL'},
    { name: 'Other', id: 'OTHER'},
    { name: 'Owners and Contractors Protective', id: 'OWNERS_AND_CONTRACTORS_PROTECTIVE'},
    { name: 'Owners, Landlords & Tenants Liability', id: 'OWNERS_LANDLORD__TENANTSK)))LIABILITY'},
    { name: 'Personal Inland Marine', id: 'PERSONAL_INLAND_MARINE'},
    { name: 'Personal package', id: 'PERSONAL_PACKAGE'},
    { name: 'Personal Umbrella', id: 'PERSONAL_UMBRELLA'},
    { name: 'Physicians And Surgeons', id: 'PHYSICIANS_AND_SURGEONS'},
    { name: 'Pollution/Environmental Liability', id: 'POLLUTION_ENVIRONMENTAL_LIABILITY'},
    { name: 'Railroad Protective Liability', id: 'RAILROAD_PROTECTIVE_LIABILITY'},
    { name: 'Recreational Vehicles', id: 'RECREATIONAL_VEHICLES'},
    { name: 'Renters (HO-4)', id: 'RENTERS__HO_4_'},
    { name: 'Scheduled property', id: 'SCHEDULED_PROPERTY'},
    { name: 'Small Farm/Ranch', id: 'SMALL_FARM_RANCH'},
    { name: 'Special Events', id: 'SPECIAL_EVENTS'},
    { name: 'Special multi-peril', id: 'SPECIAL_MULTI_PERIL'},
    { name: 'Special Risk', id: 'SPECIAL_RISK'},
    { name: 'Surety', id: 'SURETY'},
    { name: 'Transportation', id: 'TRANSPORTATION'},
    { name: 'Truckers', id: 'TRUCKERS'},
    { name: 'Valuable papers', id: 'VALUABLE_PAPERS'},
    { name: 'Watercraft (Small Boat)', id: 'WATERCRAFT_SMALL_BOAT'},
    { name: 'Wind policies', id: 'WIND_POLICIES'},
    { name: 'Workplace Violence', id: 'WORKPLACE_VIOLENCE'}
]

