export enum DateRange {
  YESTERDAY = 'YESTERDAY',
  TODAY = 'TODAY',
  WEEK_TO_DATE = 'WTD',
  LAST_WEEK = 'LAST_WEEK',
  MONTH_TO_DATE = 'MTD',
  LAST_MONTH = 'LAST_MONTH',
  QUARTER_TO_DATE = 'QTD',
  LAST_QUARTER = 'LAST_QUARTER',
  YEAR_TO_DATE = 'YTD',
  LAST_YEAR = 'LAST_YEAR',
  CUSTOM = 'CUSTOM',
}