export enum RoleType {
  ADMIN = 'ADMIN',
  LEGAL = 'LEGAL',
  MANAGER = 'MANAGER',
  SELLER = 'SELLER',
  CERTIFICATES = 'CERTIFICATES',
  ENDORSEMENTS = 'ENDORSEMENTS',
  TRAINEE = 'TRAINEE',
  OWNER = 'OWNER',
}
