export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_MODEL = 'USER_MODEL';
export const CUSTOMER_MODEL = 'CUSTOMER_MODEL';
export const INSURER_MODEL = 'INSURER_MODEL';
export const SALE_MODEL = 'SALE_MODEL';
